production:
  google_ua: UA-83866226-1
  stripe_secret_key: <%= ENV['stripe_secret_key'] %> 
  stripe_publishable_key: <%= ENV['stripe_publishable_key'] %> 

development:
  google_ua: UA-83866226-3
  stripe_secret_key: sk_test_50z8hNTDE0BsHExuI7JW7N3z
  stripe_publishable_key: pk_test_VE89rOw1wySrdQiWzrTF1uik      

test:
  google_ua: UA-83866226-2
  stripe_secret_key: sk_test_50z8hNTDE0BsHExuI7JW7N3z
  stripe_publishable_key: pk_test_VE89rOw1wySrdQiWzrTF1uik